singleuser:
  defaultUrl: "/lab"
  storage:
    dynamic:
      storageClass: csi-ceph-ssd-dp1-retain 
hub:
  config:
    Authenticator:
      admin_users:
        - admin
      allowed_users:
        - your_another_non_admin_user
#DummyAuthenticator not for production
    DummyAuthenticator:
      password: insertyourpasswordhereMVeP2VXfr
    JupyterHub:
      authenticator_class: dummy