apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  selector:
    matchLabels:
      run: auth-api
  replicas: 1
  template:
    metadata:
      labels:
        run: auth-api
    spec:
      containers:
      - name: app
        image: atemate/webinar-k8sec_auth-api:v1.7
        ports:
        - containerPort: 8080
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: auth-api-secret
              key: secret
        - name: REDIRECT_HOST
          value: http://images.vulnerable-app.seck8s.slurm.io/
        - name: DB_HOST
          value: auth-db
        - name: DB_PORT
          value: '3306'
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: database
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: password
        command: ["python", "app.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
  labels:
    run: auth-api
spec:
  selector:
    run: auth-api
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-api
spec:
  ingressClassName: nginx
  rules:
  - host: auth.vulnerable-app.seck8s.slurm.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth-api
            port:
              number: 80
