apiVersion: rbac.authorization.k8s.io/v1
# TODO: change to the role
kind: ClusterRole
metadata:
  name: deployment-reader-writer
rules:
- apiGroups:
  - "*"
  resources:
  - deployments
  verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-reader-writer
subjects:
- kind: ServiceAccount
  name: default              # <-- unintentionally grant higher privileges
  namespace: vulnerable-app  # <-- for the default SA in current namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-write-deployments
