apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: s3read-write-test-secret-cfgmap
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: mcscloud/spark-py:spark_k8s_intel
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/custom_jobs/s3read_write.py
  sparkVersion: "3.1.2"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.2
    serviceAccount: spark
    envFrom:
    - secretRef:
        name: s3-secret
    - configMapRef:
        name: s3path-config
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.2
    envFrom:
    - secretRef:
        name: s3-secret
    - configMapRef:
        name: s3path-config    
